version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/src/Reviews.API/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviewsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: src/Reviews.API/Dockerfile
    container_name: backend_api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - ./backend/src/Reviews.API/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: